
$(function(){if($('body').is('.home')){validaExibicao('#box-floater',1);}
ajaxloaderLaningPage();popCondicoes();modoExibicaoBusca();addTabEvent();addIconEvent();tituloBusca();ajustesNovoDepartamento()
ktextOverflow("div:not('.lista') .lazy .shelf-title","...");vitrineLazyLoading();vitrineImageClick();menuBuscaDinamico();ajustesMenu();cookieLogin();});$(window).scroll(function(){vitrineLazyLoading();});function ktextOverflow(obj,str){$(obj).each(function(){var texto=$(this).children().eq(0);while($(this).children().eq(0).outerHeight()>$(this).height()+3){texto.text(texto.text().replace(/\W*\s(\S)*$/,str));texto.addClass('kTextOverflow');}});}
function ajaxloaderLaningPage(){if($('#ajaxBusy').length==0){$('#page-wraper').prepend('<div id="ajaxBusy" class="load"><p>Aguarde...</p></div>');}
$(document).ajaxStart(function(){$('#ajaxBusy').show();}).ajaxStop(function(){$('#ajaxBusy').hide();});}
function alturaVitrineItem(){var heightMax;$(".prateleira-produtos ul").each(function(){heightMax=0;var ULs=$(this);$('li',ULs).each(function(){if(heightMax<$(this).height()){heightMax=$(this).height();}})
$('li',ULs).height(heightMax);})}
function loaderImgVitrine(imgPath){$(imgPath).each(function(){var imagem=this;if(!$(imagem).is('.loaded')){$(imagem).hide();$(imagem).parent().find('.loader').remove();$(imagem).parent().append('<img class="loader" src="http://www.walmart.com.br/arquivos/loader_p.gif"/>');$(imagem).addClass('loading');}});ktextOverflow("div:not('.lista') .lazy .shelf-title","...");}
function carregarImgVitrine(imgPath){var scrollTop=$(window).scrollTop()+$(window).height();$(imgPath).each(function(){var _altura=scrollTop-$(this).parent().find('.loader').offset().top;if(_altura>0){$(this).hide('fast');$(this).attr('src',$(this).attr('data-imagem'))
$(this).load(function(){$(this).parent().find('.loader').remove();$(this).removeClass('loading');$(this).addClass('loaded');$(this).fadeIn();});}});}
function vitrineLazyLoading(){loaderImgVitrine('.lazy .shelf-image img');carregarImgVitrine('.lazy .loading');}
function vitrineImageClick(){if($.browser.msie&&$.browser.version<=8){$('.shelf-image').click(function(){window.location=$(this).parent().attr('href');});}}
function ajustesNovoDepartamento(){$('.shelf-price-de').each(function(){$(this).html($(this).html()+' por');});$('.shelf-price-por').each(function(){$(this).html($(this).html().replace('Por:',''));});$('.departamento .prateleira-produtos > h2').each(function(){$(this).html('<span class="wm-spark"></span><span class="wm-titulo-sep">'+$(this).text()+'</span><span class="wm-sep-line"></span>');});$('.prateleira-produtos ul, .prateleira-promocao ul, .prateleira-produtos-big ul').each(function(){$('li:first',this).css('margin-left','0');$('li:last',this).css('margin-right','0');});$('.departamento .prateleira-produtos.n4colunas:first > ul, .departamento .prateleira-produtos.n3colunas:first > ul').css('border-bottom','0');$('.departamento .prateleira-produtos.n4colunas:eq(1) > ul:last, .departamento .prateleira-produtos.n3colunas:eq(1) > ul:last').css('border-bottom','0');$('.prateleira-produtos ul:last').css('border-bottom','0');$('.utilidades-domesticas .prateleira-produtos:eq(2) > ul:last').css('border-bottom','0');$(document).ajaxComplete(function(){$('.prateleira-produtos ul, .prateleira-promocao ul, .prateleira-produtos-big ul').each(function(){$('li:first',this).css('margin-left','0');$('li:last',this).css('margin-right','0');});});if($('body').is('.departamento')){$(document).ajaxStart(function(){$('#ajaxBusy').hide();});}}
function ajustesMenu(){$(".menu-departamento").find(".ver-filtros").html("x").show();$(".menu-departamento h4").each(function(){if($(this).next().is("ul")){$(this).append("<span></span>");}});$(".menu-departamento h3").each(function(){if($(this).next().children().size()<=0){$(this).addClass('no-children');}});$('#box-menu .search-single-navigator h5:first').before("<h5 class='lbl-filtro'>Filtrar resultados</h5>");$("#boxDropDownMarcasSelect").change(function(){if($('#boxDropDownMarcasSelect').val()!=''){window.location.href=$('#boxDropDownMarcasSelect').val()};});}
function exibicaoPrateleira(tipo){if(tipo==="lista"){$('.prateleira-produtos > .prateleira-produtos, .prateleira-produtos-big > .prateleira-produtos-big, .prateleira-promocao > .prateleira-promocao').fadeOut('fast',function(){$('#box-collection').addClass('lista');$(this).fadeIn('fast');$('.prateleira-produtos.lista ul:last li:last, .prateleira-produtos-big.lista ul:last li:last, .prateleira-promocao.lista ul:last li:last').css('border','none');$('.flags-collection').each(function(){if($(this).children(':visible').size()===0){$(this).hide()}});})
$('.tabela-btn').removeClass('ativo');$('.lista-btn').addClass('ativo');}else if(tipo==="tabela"){$('.prateleira-produtos > .prateleira-produtos, .prateleira-produtos-big > .prateleira-produtos-big, .prateleira-promocao > .prateleira-promocao').fadeOut('fast',function(){$('#box-collection').removeClass('lista')
$(this).fadeIn('fast');})
$('.lista-btn').removeClass('ativo');$('.tabela-btn').addClass('ativo');}}
function modoExibicaoBusca(){$('.lista-btn').click(function(){exibicaoPrateleira('lista')});$('.tabela-btn').click(function(){exibicaoPrateleira('tabela')});if($('.busca-vazio').size()>0){$('.busca-modo-exibicao').hide();}
$(function(){if($('.page-number').size()<=2){$('.pager, .lbl-paginas').hide();}else{$('.pager, .lbl-paginas').show();}})}
function tituloBusca(){if($('body').is('.busca-resultado')){var qtd=$('.produtos-encontrados-paginacao p:first').text().replace('Produtos encontrados: ','');var termo=$('.titulo-sessao').text().replace('Resultado da Busca: ','');var fraseResultado=termo===''?'Foram encontrados '+qtd+' resultados':'Foram encontrados '+qtd+' resultados para o termo '+termo;if($('.busca-vazio').size()<1){$('.titulo-sessao').html(fraseResultado);}
$('.busca-resultado #box-collection').addClass('lista');$('.tabela-btn').removeClass('ativo');$('.lista-btn').addClass('ativo');}}
function popCondicoes(){$(".popCondicoesFrete").click(function(e){e.preventDefault();$('#boxPopUpCondicoes').modal({overlayClose:true});return false;});$("#btn-Fechar").hide();}
function addTabEvent(){$("#menu-categorias a").click(function(){showHideTabs("categorias");return false;});$("#menu-atendimento a").click(function(){showHideTabs("atendimento");return false;});}
function showHideTabs(tab){$('.boxContainerTabs').slideUp();$("li, li a").removeClass("ativo");if($("#box-"+tab+"").is(":hidden")){$("#box-"+tab+"").slideToggle();$("#menu-"+tab+", #menu-"+tab+" a").toggleClass("ativo");}}
function addIconEvent(){$("#ico-atendimento .atendShowHide").click(function(){$("#ico-atendimento .atendShowHide").toggle();});$("#acessib-ico").mouseover(function(){$("#acessib-pop").fadeIn();});$("#acessib-ico").mouseout(function(){$("#acessib-pop").fadeOut();});}
function menuBuscaDinamico(){var pathName=window.location.pathname;var protocol=window.location.protocol;var host=window.location.hostname;if(typeof(menuhotsite)!="undefined"){if(menuhotsite===true){if(pathName!="/busca"){$('.menu-departamento a').each(function(){$(this).attr('href',protocol+"//"+host+pathName+'?'+$(this).attr('href').split('?')[1])});}}}}
var wmcookie={criar:function(nome,value,dias){var exemplo="wmcookie.criar('teste','opa','25/10/2012-8:00')";if(dias){if(dias.length>3){var saida=dias;var saidaD=saida.split('/');var saidaH=saidaD[2].split('-')[1].split(':');dia=parseInt(saidaD[0]);mes=parseInt(saidaD[1]);ano=parseInt(saidaD[2]);hora=parseInt(saidaH[0]);minuto=parseInt(saidaH[1]);var data=new Date();data.setUTCDate(dia);data.setUTCMonth(mes-1);data.setUTCFullYear(ano);data.setUTCHours(hora+2);data.setUTCMinutes(minuto);data.setUTCSeconds(00);var expires="; expires="+data.toGMTString();}else{var data=new Date();data.setTime(data.getTime()+(dias*24*60*60*1000));var expires="; expires="+data.toGMTString();}}else{var expires="";}
document.cookie=nome+"="+value+expires+"; path=/";},ler:function(nome){var nomeEQ=nome+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nomeEQ)==0)return c.substring(nomeEQ.length,c.length);}
return nomeEQ;},apagar:function(nome){wmcookie.criar(nome,"",-1);}}
function cookieLogin(){if($("#lblLoginMsg").is(':visible')){var agora=new Date;agora=agora.getDate()+"/"+agora.getMonth()+"/"+agora.getFullYear()+"-"+agora.getHours()+":"+agora.getMinutes()+":"+agora.getSeconds();wmcookie.criar("login",agora,90);wmcookie.apagar("login");}}
function validaExibicao(target,n){var data=new Date();var dataExp=(data.getDate()+1)+'/'+(data.getUTCMonth()+1)+'/'+data.getUTCFullYear()+'-8:00';var obj=target.replace('#','');var exibicoes=wmcookie.ler(obj);exibicoes=exibicoes==="false"?false:parseInt(exibicoes,10);if(exibicoes===false){$(target).remove();}
if(exibicoes===false){return false}
if(isNaN(exibicoes)){wmcookie.criar(obj,1,dataExp);exibicoes=parseInt(wmcookie.ler(obj),10);if(exibicoes===n){wmcookie.criar(obj,false,dataExp);}}else{wmcookie.criar(obj,exibicoes+1,dataExp);if(exibicoes===(n-1)){wmcookie.criar(obj,false,dataExp);}}}
function contaClick(_campanha,_container){var container=_container!==undefined?_container:'#wm-content';if(_campanha!==""||_campanha!==undefined){s.tl(this,'o',_campanha+' : PageView');}
$('a',container).each(function(){$(this).click(function(e){var _this=$(this);var title=_this.attr('title');var href=_this.attr('href');var linkID;if(title!==undefined||title!==''){linkID=title;}else{linkID=href;}
var linkName=removeAcento(_campanha)+' : '+removeAcento(linkID);if(!$(this).is('.ignore')){s.tl(this,'o',linkName);}});});}
function removeAcento(text){text=text.replace(new RegExp('[ÃÃ€Ã‚ÃƒÃ„]','g'),'A');text=text.replace(new RegExp('[Ã¡Ã Ã¢Ã£Ã¤]','g'),'a');text=text.replace(new RegExp('[Ã‰ÃˆÃŠÃ‹]','g'),'E');text=text.replace(new RegExp('[Ã©Ã¨ÃªÃ«]','g'),'e');text=text.replace(new RegExp('[ÃÃŒÃŽÃ]','g'),'I');text=text.replace(new RegExp('[Ã­Ã¬Ã®Ã¯]','g'),'i');text=text.replace(new RegExp('[Ã“Ã’Ã”Ã•Ã–]','g'),'O');text=text.replace(new RegExp('[Ã³Ã²Ã´ÃµÃ¶]','g'),'o');text=text.replace(new RegExp('[ÃšÃ™Ã›Ãœ]','g'),'U');text=text.replace(new RegExp('[ÃºÃ¹Ã»Ã¼]','g'),'u');text=text.replace(new RegExp('[Ã‡]','g'),'C');text=text.replace(new RegExp('[Ã§]','g'),'c');return text;}

